import { AppHeader } from "@/components/app-header";
import { AppSidebar } from "@/components/app-sidebar";
import { Providers } from "@/components/providers";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "My Kid Hub",
  description: "Generated by create next app",
};

export default function PlatformLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <>
            <AppHeader />
            <div className="flex flex-1 flex-col gap-4 p-4">{children}</div>
          </>
        </SidebarInset>
      </SidebarProvider>
    </Providers>
  );
}
