import { AppSidebar } from "@/components/layout/app-sidebar";
import { Providers } from "@/components/providers";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { SchoolService } from "@/lib/school/school.service";
import { getSession } from "@/lib/utils/session";
import { Organization, User } from "@prisma/client";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "My Kid Hub",
  description: "Generated by create next app",
};

export default async function PlatformLayout({
  breadcrumb,
  children,
}: Readonly<{
  breadcrumb: React.ReactNode;
  children: React.ReactNode;
}>) {
  const data = await getSession();
  const user = data?.user as User;
  const school = (await SchoolService.findSchoolById(
    data?.session.activeOrganizationId || ""
  )) as Organization;

  return (
    <Providers>
      <SidebarProvider>
        <AppSidebar school={school} user={user} />
        <SidebarInset>
          <>
            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12 border-b">
              <div className="flex items-center gap-2 px-4">
                <SidebarTrigger className="-ml-1" />
                <Separator orientation="vertical" className="mr-2 h-4" />
                {breadcrumb}
              </div>
            </header>
            <div className="flex flex-1 flex-col gap-4 p-4">{children}</div>
          </>
        </SidebarInset>
      </SidebarProvider>
    </Providers>
  );
}
