version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: mykidhub_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mykidhub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
